# Generated by Django 5.2.11 on 2026-02-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_moduleprogress_resourceprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprogress',
            name='last_position_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceprogress',
            name='watch_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
