# Generated by Django 5.2.11 on 2026-02-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_resourceprogress_last_position_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignment_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='has_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='has_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
